language: node_js

node_js:
  - 14

cache:
  directories:
    - ~/.npm

script:
    - npm test

after_success:
  - node node_modules/.bin/jest --coverage --config jest-config.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage